algo:
  detection_backend: [classical]
  dimred: [raw]
  feature_map_approx_method: [raw]
  regime_detection_algorithm: [jump_model]
  regimes: [3]
  jump_penalty: [5.0]
  jump_max_iter: [20]
  random_state: [42]
  post_processing_method: [majority_voting]
  min_regime_length: [20]
  include_last_regime: [true]

metrics:
  mode: write
  dir: ${IMG_DIR}
  plot: true
  explainability_features: ["__auto__"]
  features_to_plot: ["__auto__"]

log:
  dir: ${LOG_DIR}
  level: INFO
