algo:
  dimred: [raw]
  feature_map_approx_method: [raw]
  regime_detection_algorithm: [hmm]
  hmm_emissions: [gaussian]
  regimes: [3]
  hmm_n_iter: [50]
  post_processing_method: [no_post_processing]
  min_regime_length: [1]
  include_last_regime: [true]

metrics:
  mode: write
  dir: ${IMG_DIR}
  plot: true
  explainability_features: ["__auto__"]
  features_to_plot: ["__auto__"]

log:
  dir: ${LOG_DIR}
  level: INFO
